# Generated by Django 4.2.4 on 2023-08-10 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekskavat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ekskavator',
            options={'verbose_name': 'Экскаватор-погрузчик', 'verbose_name_plural': 'Экскаваторы-погрузчики'},
        ),
    ]
