# Generated by Django 4.2.4 on 2023-08-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekskavat', '0003_ekskavator_dimension_ekskavator_do_wya_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekskavator',
            name='do_wya',
        ),
        migrations.RemoveField(
            model_name='ekskavator',
            name='p',
        ),
        migrations.AddField(
            model_name='ekskavator',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Разряд'),
        ),
        migrations.AddField(
            model_name='ekskavator',
            name='depth',
            field=models.CharField(blank=True, default='500', max_length=50, null=True, verbose_name='Двигатель'),
        ),
        migrations.AddField(
            model_name='ekskavator',
            name='m_unload_height',
            field=models.CharField(blank=True, default='3 метра', max_length=50, null=True, verbose_name='Максимальная высота разгрузки'),
        ),
        migrations.AddField(
            model_name='ekskavator',
            name='m_unload_range',
            field=models.CharField(blank=True, default='3 метра', max_length=50, null=True, verbose_name='Максимальная дальность разгрузки'),
        ),
        migrations.AddField(
            model_name='ekskavator',
            name='unload_height',
            field=models.CharField(blank=True, default='3 метра', max_length=50, null=True, verbose_name='Высота разгрузки'),
        ),
        migrations.AlterField(
            model_name='ekskavator',
            name='ru_title',
            field=models.CharField(default='Экскаватор-погрузчик', max_length=50, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='ekskavator',
            name='title',
            field=models.CharField(default='ekskavator ', max_length=50, verbose_name='Название'),
        ),
    ]
