# Generated by Django 4.2.4 on 2023-08-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekskavat', '0004_remove_ekskavator_do_wya_remove_ekskavator_p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekskavator',
            name='depth',
        ),
    ]
