# Generated by Django 4.2.4 on 2023-08-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekskavat', '0005_remove_ekskavator_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekskavator',
            name='depth',
            field=models.CharField(blank=True, default='500', max_length=50, null=True, verbose_name='Глубина'),
        ),
    ]
