# Generated by Django 4.2.4 on 2023-08-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0002_beton_dimension_beton_direction_beton_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beton',
            name='ru_title',
            field=models.CharField(default='Бетоносмеситель', max_length=50, verbose_name='Название на русском'),
        ),
    ]
