# Generated by Django 4.2.4 on 2023-08-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beton', '0003_alter_beton_ru_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='beton',
            name='mixer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Объем смесиьеля'),
        ),
    ]
