# Generated by Django 4.2.4 on 2023-08-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vil_pogruz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vil_pogruz',
            name='climb_angle',
            field=models.CharField(blank=True, default='3 тонны', max_length=50, null=True, verbose_name='Угол подъема'),
        ),
        migrations.AddField(
            model_name='vil_pogruz',
            name='dimension',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Габариты'),
        ),
        migrations.AddField(
            model_name='vil_pogruz',
            name='engine',
            field=models.CharField(blank=True, default='500', max_length=50, null=True, verbose_name='Двигатель'),
        ),
        migrations.AddField(
            model_name='vil_pogruz',
            name='mass',
            field=models.CharField(blank=True, default='3 тонны', max_length=50, null=True, verbose_name='Масса'),
        ),
        migrations.AddField(
            model_name='vil_pogruz',
            name='tire',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Размер шин'),
        ),
        migrations.AddField(
            model_name='vil_pogruz',
            name='turning_radius',
            field=models.CharField(blank=True, default='3 метра', max_length=50, null=True, verbose_name='Радиус разворота'),
        ),
        migrations.AddField(
            model_name='vil_pogruz',
            name='unload_height',
            field=models.CharField(blank=True, default='3 метра', max_length=50, null=True, verbose_name='Высота разгрузки'),
        ),
        migrations.AddField(
            model_name='vil_pogruz',
            name='wheels',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Колесная база'),
        ),
        migrations.AddField(
            model_name='vil_pogruz',
            name='width',
            field=models.CharField(blank=True, default='3 тонны', max_length=50, null=True, verbose_name='Длинна вил'),
        ),
        migrations.AlterField(
            model_name='vil_pogruz',
            name='state',
            field=models.CharField(default='под заказ', max_length=50, verbose_name='Состояние'),
        ),
    ]
