# Generated by Django 4.2.4 on 2023-08-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svayboy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='svayboy',
            options={'verbose_name': 'Своебойная машина', 'verbose_name_plural': 'Своебойные машины'},
        ),
    ]
