# Generated by Django 4.2.4 on 2023-08-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svayboy', '0002_alter_svayboy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svayboy',
            name='image2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='svayboy',
            name='image3',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='svayboy',
            name='image4',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='svayboy',
            name='image5',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
