# Generated by Django 4.2.4 on 2023-08-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svayboy', '0003_alter_svayboy_image2_alter_svayboy_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svayboy',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='svayboy',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='svayboy',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='svayboy',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
