# Generated by Django 4.2.4 on 2023-08-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svayboy', '0006_alter_svayboy_ru_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svayboy',
            name='image1',
            field=models.ImageField(upload_to='imag/'),
        ),
        migrations.AlterField(
            model_name='svayboy',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='imag/'),
        ),
        migrations.AlterField(
            model_name='svayboy',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='imag/'),
        ),
        migrations.AlterField(
            model_name='svayboy',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='imag/'),
        ),
        migrations.AlterField(
            model_name='svayboy',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='imag/'),
        ),
    ]
