# Generated by Django 4.2.4 on 2023-08-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svayboy', '0007_alter_svayboy_image1_alter_svayboy_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='svayboy',
            name='dimension',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Габариты'),
        ),
        migrations.AddField(
            model_name='svayboy',
            name='do_wya',
            field=models.CharField(blank=True, default='Ручная механическая коробка', max_length=50, null=True, verbose_name='Способ езды'),
        ),
        migrations.AddField(
            model_name='svayboy',
            name='engine',
            field=models.CharField(blank=True, default='500', max_length=50, null=True, verbose_name='Двигатель'),
        ),
        migrations.AddField(
            model_name='svayboy',
            name='fuel',
            field=models.CharField(blank=True, default='42 кВт', max_length=50, null=True, verbose_name='Расход топлива'),
        ),
        migrations.AddField(
            model_name='svayboy',
            name='mass',
            field=models.CharField(blank=True, default='3 тонны', max_length=50, null=True, verbose_name='Масса'),
        ),
        migrations.AddField(
            model_name='svayboy',
            name='p',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Давление гидравлического насоса'),
        ),
        migrations.AddField(
            model_name='svayboy',
            name='power',
            field=models.CharField(blank=True, default='42 кВт', max_length=50, null=True, verbose_name='Мощность'),
        ),
        migrations.AddField(
            model_name='svayboy',
            name='v',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Скорость движения'),
        ),
        migrations.AddField(
            model_name='svayboy',
            name='wheels',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Колесная база'),
        ),
        migrations.AlterField(
            model_name='svayboy',
            name='state',
            field=models.CharField(default='под заказ', max_length=50, verbose_name='Состояние'),
        ),
    ]
