# Generated by Django 4.2.4 on 2023-08-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone_number', models.IntegerField(verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
                ('message', models.CharField(max_length=250, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Заявка на звонок',
                'verbose_name_plural': 'Заявки на звонки',
            },
        ),
    ]
