# Generated by Django 4.2.4 on 2023-08-24 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_calls_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 24, 11, 42, 31, 856303, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
