# Generated by Django 4.2.4 on 2023-08-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_calls_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время отправки'),
        ),
    ]
