# Generated by Django 4.2.4 on 2023-08-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_calls_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='message',
            field=models.CharField(max_length=250, verbose_name='Сообщениеttt'),
        ),
    ]
