# Generated by Django 4.2.4 on 2023-08-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_calls_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone_number', models.IntegerField(verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
                ('message', models.CharField(max_length=250, verbose_name='Сообщениеttt')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('time1', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
            ],
            options={
                'verbose_name': 'Заявка на звонок',
                'verbose_name_plural': 'Заявки на звонки',
            },
        ),
        migrations.DeleteModel(
            name='Calls',
        ),
    ]
