# Generated by Django 4.2.4 on 2023-08-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pogruz', '0002_pogruz'),
    ]

    operations = [
        migrations.AddField(
            model_name='pogruz',
            name='bucket_width',
            field=models.CharField(default='2 метра', max_length=50, verbose_name='Ширина ковша'),
        ),
        migrations.AddField(
            model_name='pogruz',
            name='control_level',
            field=models.CharField(default='Механический рычаг управления', max_length=50, verbose_name='Рычаг управления'),
        ),
        migrations.AddField(
            model_name='pogruz',
            name='dimension',
            field=models.CharField(default='', max_length=50, verbose_name='Габариты'),
        ),
        migrations.AddField(
            model_name='pogruz',
            name='engine',
            field=models.CharField(default='500', max_length=50, verbose_name='Двигатель'),
        ),
        migrations.AddField(
            model_name='pogruz',
            name='mass',
            field=models.CharField(default='3 тонны', max_length=50, verbose_name='Масса'),
        ),
        migrations.AddField(
            model_name='pogruz',
            name='power',
            field=models.CharField(default='42 кВт', max_length=50, verbose_name='Мощность'),
        ),
        migrations.AddField(
            model_name='pogruz',
            name='transmission',
            field=models.CharField(default='Ручная механическая коробка', max_length=50, verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='pogruz',
            name='unload_height',
            field=models.CharField(default='3 метра', max_length=50, verbose_name='Высота разгрузки'),
        ),
        migrations.AddField(
            model_name='pogruz',
            name='wheels',
            field=models.CharField(default='', max_length=50, verbose_name='Колеса'),
        ),
    ]
