# Generated by Django 4.2.4 on 2023-08-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pogruz', '0003_pogruz_bucket_width_pogruz_control_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pogruz',
            name='stop',
            field=models.CharField(default='', max_length=50, verbose_name='Тормозная система'),
        ),
    ]
