# Generated by Django 4.2.4 on 2023-08-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pogruz', '0004_pogruz_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pogruz',
            name='bucket_width',
            field=models.CharField(blank=True, default='2 метра', max_length=50, null=True, verbose_name='Ширина ковша'),
        ),
        migrations.AlterField(
            model_name='pogruz',
            name='control_level',
            field=models.CharField(blank=True, default='Механический рычаг управления', max_length=50, null=True, verbose_name='Рычаг управления'),
        ),
        migrations.AlterField(
            model_name='pogruz',
            name='dimension',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Габариты'),
        ),
        migrations.AlterField(
            model_name='pogruz',
            name='engine',
            field=models.CharField(blank=True, default='500', max_length=50, null=True, verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='pogruz',
            name='mass',
            field=models.CharField(blank=True, default='3 тонны', max_length=50, null=True, verbose_name='Масса'),
        ),
        migrations.AlterField(
            model_name='pogruz',
            name='power',
            field=models.CharField(blank=True, default='42 кВт', max_length=50, null=True, verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='pogruz',
            name='state',
            field=models.CharField(default='под заказ', max_length=50, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='pogruz',
            name='stop',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Тормозная система'),
        ),
        migrations.AlterField(
            model_name='pogruz',
            name='transmission',
            field=models.CharField(blank=True, default='Ручная механическая коробка', max_length=50, null=True, verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='pogruz',
            name='unload_height',
            field=models.CharField(blank=True, default='3 метра', max_length=50, null=True, verbose_name='Высота разгрузки'),
        ),
        migrations.AlterField(
            model_name='pogruz',
            name='wheels',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Колесная база'),
        ),
    ]
